name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-matrix:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    uses: ./.github/workflows/ci-shared.yml
    with:
      python-version: ${{ matrix.python-version }}
      run-tests: true
      run-lint: false
      upload-coverage: ${{ matrix.python-version == '3.11' }}
      build-package: false